[project]
dependencies = []
name = "anticipatory-action"
requires-python = ">= 3.10"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge", "wfp-ram"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
anticipatory_action = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
hip-analysis = ">=0.12.0,<0.13"
hdc-algo = ">=0.5.0,<0.6"

[tool.pixi.environments]
test = { features = ["test"], solve-group = "prod" }
default = { features = ["dev", "test"], solve-group = "prod" }
prod = { solve-group = "prod" }

[tool.pixi.feature.dev.dependencies]
jupyterlab = "*"
pixi-kernel = "*"
ipykernel = "*"
jupytext = "*"

[tool.pixi.feature.test.dependencies]
pytest = ">=8.3.5,<9"

[dependency-groups]
test = ["pytest"]
