[project]
dependencies = []
name = "anticipatory-action"
requires-python = ">= 3.10"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["AA"]

[tool.pixi.workspace]
channels = ["conda-forge", "wfp-ram"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64", "linux-aarch64"]

[tool.pixi.pypi-dependencies]
anticipatory_action = { path = ".", editable = true }

[tool.pixi.dependencies]
python = "3.10.*"
hip-analysis = ">=0.12.0,<0.13"
numpy = "<2.0"
xclim = "0.53.1.*"

[tool.pixi.environments]
test = { features = ["test"], solve-group = "prod" }
default = { features = ["dev", "test"], solve-group = "prod" }
production = { solve-group = "prod" }

[tool.pixi.feature.dev.dependencies]
jupyterlab = "*"
pixi-kernel = "*"
ipykernel = "*"
jupytext = "*"

[tool.pixi.feature.test.dependencies]
pytest = ">=8.3.5,<9"

[dependency-groups]
test = ["pytest"]

[tool.pixi.tasks.docker-build]
description = "Build the Docker image for Anticipatory Action"
cmd = "docker build -t aa-runner ."

[tool.pixi.tasks.docker-operational]
description = "Run operational script via Docker"
args = ["country", "index", "issue"]
cmd = [
  "docker", "run", "--rm",
  "-e", "MODE=operational",
  "-e", "COUNTRY={{ country }}",
  "-e", "INDEX={{ index }}",
  "-e", "ISSUE={{ issue }}",
  "aa-runner"
]

[tool.pixi.tasks.docker-analytical]
description = "Run analytical script via Docker"
args = ["country", "index"]
cmd = [
  "docker", "run", "--rm",
  "-e", "MODE=analytical",
  "-e", "COUNTRY={{ country }}",
  "-e", "INDEX={{ index }}",
  "aa-runner"
]

[tool.pixi.tasks.docker-triggers]
description = "Run trigger script via Docker"
args = ["country", "index", "vulnerability"]
cmd = [
  "docker", "run", "--rm",
  "-e", "MODE=triggers",
  "-e", "COUNTRY={{ country }}",
  "-e", "INDEX={{ index }}",
  "-e", "VULNERABILITY={{ vulnerability }}",
  "aa-runner"
]