# Issue month: months corresponding to the forecasts used for monitoring
issue_months:
  - "06"
  - "07"
  - "08"
  - "09"
  - "10"
  - "11"
  - "12"
  - "01"
  - "02"

# First year of season to monitor operationally (e.g. 2024 for 2024/2025 season)
monitoring_year: 2025

# Last year of calibration period used for triggers selection (e.g. 2022 for 1981-2022)
calibration_year: 2022

# Minimum length of indicator periods (ON, NDJ, JFMA...)
min_index_period: 3

# Maximum length of indicator periods (ON, NDJ, JFMA...)
max_index_period: 3

# First month of the wet season
start_season: 10

# Last month of the wet season
end_season: 6

# Start date of historical time series used in anomaly computation
hist_anomaly_start: null

# End date of historical time series used in anomaly computation
hist_anomaly_stop: "2018-12-31"

# Save (and overwrite if exists) ds (obs or probs) for future trigger choice
save_zarr: true

# Thresholds defining different drought intensities used in probabilities computation
intensity_thresholds:
  Severe: -1
  Moderate: -0.85
  Mild: -0.68
  Normal: -0.44
  

# Vulnerability class of triggers for each district: general or non-regret (GT or NRT)
districts_vulnerability: 
    Chirundu: "TBD"
    Chongwe: "TBD"
    Chisamba: "TBD"
    Sesheke: "TBD"
    Mwandi: "TBD"
    Sioma: "TBD"
    Zimba: "TBD"
    Kapiri Mposhi: "TBD"
    Serenje: "TBD"
    Chikankanta: "TBD"
    Pemba: "TBD"
    Shangombo: "TBD"
    Livingstone: "TBD"
    Sinazongwe: "TBD"
    Gwembe: "TBD"
    Kalomo: "TBD"
    Kazungula: "TBD"
    Siavonga: "TBD"
    Monze: "TBD"
    Mazabuka: "TBD"
    Mulobezi: "TBD"
    Itezhi-tezhi: "TBD"
    Kafue: "TBD"
    Luangwa: "TBD"
    Rufunsa: "TBD"
    Nyimba: "TBD"
    Luano: "TBD"
    Mambwe: "TBD"
    Chitambo: "TBD"
    Mpika: "TBD"
    Masaiti: "TBD"
    Nkeyema: "TBD"
    Sinda: "TBD"
    Chilanga: "TBD"
    Vubwi: "TBD"
    Shibuyunji: "TBD"
    # Lusaka: "TBD"
    Chibombo: "TBD"
    Kabwe: "TBD"
    Mumbwa: "TBD"
    Chadiza: "TBD"
    Ngabwe: "TBD"
    Mpongwe: "TBD"
    Chipata: "TBD"
    Mufumbwe: "TBD"
    Kasempa: "TBD"
    Chama: "TBD"
    Shiwamg'andu: "TBD"
    Nalolo: "TBD"
    Sikongo: "TBD"
    Limulunga: "TBD"
    Kabompo: "TBD"
    Mongu: "TBD"
    Kalabo: "TBD"
    Kaoma: "TBD"
    Lukulu: "TBD"

# Tolerance for thresholds for each category, used to compute false alarm with tolerance
tolerance:
  Normal: 0
  Mild: -0.44
  Moderate: -0.68
  Severe: -0.85

# Skill requirements for General Triggers
general_t:
  HR: 0.5  # W/out exceptions: HR=0.55
  SR: 0.55
  FR: 0.45
  RP: 4.0

# Skill requirements for Non Regret Triggers
non_regret_t:
  HR: 0.5  # W/out exceptions: HR=0.70
  SR: 0.
  FR: 0.5
  RP: 2.0

# Window definitions for SPI and DRYSPELL indicators
windows:
  spi:
    window1: ["OND", "NDJ"]
    window2: ["DJF", "JFM"]
  dryspell:
    window1: []
    window2: ["DJ", "JF", "FM"]