name: Run CI Tests
on:
  # Run on all pull requests and on pushes to main and dev.
  pull_request:
  push:
    branches:
      - main

env:
  AWS_REGION: "eu-central-1"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: true
    permissions:
      id-token: write # required for requesting the JWT for AWS authentication
      contents: read # required for actions/checkout
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - name: Install environment with pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.43.0
        # Automatically detects changes in pixi.lock and, if so, updates environment
        cache: true
        environments: >-
          test
    
    - name: Check code formatting
      shell: bash -l {0}
      continue-on-error: true
      run: |
        pixi run lint-check
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_GHA_ROLE }}  # Added manually to GitHub repo
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    - name: Run tests
      shell: bash -l {0}
      run: |
        pixi run pytest 